In [21]:
mat = [[1,2,3], [4,5,6], [7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
sec_col = [k[1] for k in mat]
sec_col

[2, 5, 8]

In [23]:
import numpy as np

In [24]:
arr = np.array(mat)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.shape

(3, 3)

In [56]:
arr.size

9

In [58]:
arr.sum()/arr.size

5.0

In [59]:
arr.mean()

5.0

In [27]:
arr.dtype

dtype('int32')

In [30]:
arr = arr.astype('float')

In [31]:
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [74]:
nums = [1,2,3,4,5]

In [75]:
arr1d = np.array(nums)
arr1d.shape

(5,)

In [76]:
arr1d.T.shape

(5,)

In [36]:
arr1d.shape

(5,)

In [77]:
RV = arr1d.reshape(1, -1)
RV

array([[1, 2, 3, 4, 5]])

In [78]:
RV.shape

(1, 5)

In [79]:
CV = RV.T
CV

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [80]:
CV.shape

(5, 1)

In [49]:
arr1d.mean()

3.0

In [50]:
RV.mean()

3.0

In [52]:
CV.mean()

3.0

In [55]:
RV.size

5

In [54]:
arr1d.size

5

In [63]:
CV = arr1d.reshape(-1, 1)
CV

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [84]:
np.log10(10)

1.0

In [85]:
np.log10(arr1d)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [86]:
np.log10(RV)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ]])

In [87]:
np.log10(CV)

array([[0.        ],
       [0.30103   ],
       [0.47712125],
       [0.60205999],
       [0.69897   ]])

In [111]:
np.random.seed(101)
A = np.random.randint(0,100,16).reshape(4,4)
A

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [113]:
A.shape

(4, 4)

In [118]:
B = A[0]
B.shape

(4,)

In [122]:
A.dot(B)

(4,)

In [123]:
A.dot(B.reshape(1,-1))

ValueError: shapes (4,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [124]:
A.dot(B.reshape(-1,1))

array([[20607],
       [13647],
       [12489],
       [16392]])

In [126]:
np.matmul(A,B.reshape(-1,1))

array([[20607],
       [13647],
       [12489],
       [16392]])

In [128]:
np.linalg.inv(A)

array([[ 0.00925035,  0.00717036,  0.00304372, -0.01412207],
       [-0.0120236 ,  0.0060894 ,  0.00709183,  0.00531347],
       [ 0.00666853,  0.00177566, -0.01179111,  0.00406347],
       [-0.00409535, -0.0127428 ,  0.0083988 ,  0.01362868]])

In [130]:
np.linalg.det(A)

-38865551.99999996

In [140]:
X = np.array([[1, 1],[1,3], [1,5]])
X

array([[1, 1],
       [1, 3],
       [1, 5]])

In [141]:
Y = np.array([4.8, 11.3, 17.2]).reshape(-1,1)
Y

array([[ 4.8],
       [11.3],
       [17.2]])

In [142]:
np.linalg.inv(X.T.dot(X))

array([[ 1.45833333, -0.375     ],
       [-0.375     ,  0.125     ]])

In [143]:
np.linalg.inv(X.T.dot(X)).dot(X.T)

array([[ 1.08333333,  0.33333333, -0.41666667],
       [-0.25      ,  0.        ,  0.25      ]])

In [146]:
W = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)
W

array([[1.8],
       [3.1]])

In [147]:
X.dot(W)

array([[ 4.9],
       [11.1],
       [17.3]])

In [152]:
X = np.array([1,3,5]).reshape(-1,1)
X

array([[1],
       [3],
       [5]])

In [153]:
Y

array([[ 4.8],
       [11.3],
       [17.2]])

In [154]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()

In [155]:
LR.fit(X,Y)

LinearRegression()

In [156]:
LR.coef_

array([[3.1]])

In [157]:
LR.intercept_

array([1.8])

In [159]:
LR.predict(X)

array([[ 4.9],
       [11.1],
       [17.3]])

## NumPY Functions

In [160]:
A

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [161]:
A[0]

array([95, 11, 81, 70])

In [162]:
A[-1]

array([40, 60, 92, 64])

In [164]:
A[1,1] # [row,col] indexing

87

In [166]:
A[-1, :]  #all the col of the last row (entire last row)

array([40, 60, 92, 64])

In [167]:
A[:,1]  # all rows, of the second col

array([11, 87, 40, 60])

In [168]:
A[:,:]

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [169]:
A[:]

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [170]:
A[:3]

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63]])

In [171]:
A[1:3, 1:3]  # elements in the second and third row, second and third col

array([[87, 75],
       [40,  4]])

In [172]:
A[[1,3], [0,2]]

array([63, 92])

In [174]:
A>50

array([[ True, False,  True,  True],
       [ True,  True,  True, False],
       [ True, False, False,  True],
       [False,  True,  True,  True]])

In [178]:
A[(A>50) & (A<80)]

array([70, 63, 75, 77, 63, 60, 64])

In [180]:
A.flatten().shape

(16,)

In [181]:
A.ravel().shape

(16,)

In [183]:
A

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [182]:
A.trace()

250

In [184]:
A.diagonal()

array([95, 87,  4, 64])

In [185]:
np.fliplr(A).diagonal()

array([70, 75, 40, 40])

In [186]:
np.flipud(A).diagonal()

array([40, 40, 75, 70])

In [187]:
v = [1,2,3,4,5]
np.diag(v)   #create a diagonal matrix 

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [188]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [189]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [191]:
np.zeros(A.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [192]:
np.ones(A.shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [194]:
np.ones(A.shape)*np.nan

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [198]:
np.eye(4)

TypeError: 'tuple' object cannot be interpreted as an integer

In [200]:
A.dot(np.eye(A.shape[0]))

array([[95., 11., 81., 70.],
       [63., 87., 75.,  9.],
       [77., 40.,  4., 63.],
       [40., 60., 92., 64.]])

In [201]:
A.min()

4

In [203]:
A.argmin()

10

In [213]:
A1 = A[:3, :2]
A1

array([[95, 11],
       [63, 87],
       [77, 40]])

In [214]:
A1.min(), A1.argmin()

(11, 1)

In [219]:
A.mean(), A.std(), A.var().round(2)

(58.1875, 28.45219400591104, 809.53)

In [220]:
A

array([[95, 11, 81, 70],
       [63, 87, 75,  9],
       [77, 40,  4, 63],
       [40, 60, 92, 64]])

In [225]:
np.sin(A).round(3)

array([[ 0.683, -1.   , -0.63 ,  0.774],
       [ 0.167, -0.822, -0.388,  0.412],
       [ 1.   ,  0.745, -0.757,  0.167],
       [ 0.745, -0.305, -0.779,  0.92 ]])

In [226]:
np.log10(A).round(1)

array([[2. , 1. , 1.9, 1.8],
       [1.8, 1.9, 1.9, 1. ],
       [1.9, 1.6, 0.6, 1.8],
       [1.6, 1.8, 2. , 1.8]])

In [227]:
np.exp(A)

array([[1.81123908e+41, 5.98741417e+04, 1.50609731e+35, 2.51543867e+30],
       [2.29378316e+27, 6.07603023e+37, 3.73324200e+32, 8.10308393e+03],
       [2.75851345e+33, 2.35385267e+17, 5.45981500e+01, 2.29378316e+27],
       [2.35385267e+17, 1.14200739e+26, 9.01762841e+39, 6.23514908e+27]])

In [228]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [230]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [232]:
np.arange(0,10,1.99)

array([0.  , 1.99, 3.98, 5.97, 7.96, 9.95])

In [240]:
np.linspace(0, 10).round(2)

array([ 0.  ,  0.2 ,  0.41,  0.61,  0.82,  1.02,  1.22,  1.43,  1.63,
        1.84,  2.04,  2.24,  2.45,  2.65,  2.86,  3.06,  3.27,  3.47,
        3.67,  3.88,  4.08,  4.29,  4.49,  4.69,  4.9 ,  5.1 ,  5.31,
        5.51,  5.71,  5.92,  6.12,  6.33,  6.53,  6.73,  6.94,  7.14,
        7.35,  7.55,  7.76,  7.96,  8.16,  8.37,  8.57,  8.78,  8.98,
        9.18,  9.39,  9.59,  9.8 , 10.  ])

In [238]:
np.logspace(0,3, 10).round(2)

array([   1.  ,    2.15,    4.64,   10.  ,   21.54,   46.42,  100.  ,
        215.44,  464.16, 1000.  ])